  "home.brandTagline": "Premium catering, intelligently matched.",
  "home.nav.browse": "Browse Caterers",
  "home.nav.howItWorks": "How It Works",
  "home.nav.whySpeisely": "Why Speisely",
  "home.nav.login": "Login",
  "home.badge": "AI-guided catering discovery",
  "home.heroTitle": "Premium catering for weddings, business events, and private occasions.",
  "home.heroSubtitle": "Speisely helps you discover caterers, plan your event, and continue through a clearer, more premium booking journey.",
  "home.cta.dashboard": "Dashboard",
  "home.cta.planEvent": "Plan an Event",
  "home.cta.startRequest": "Start Your Event Request",
  "home.cta.browse": "Browse Caterers",
  "home.chips.wedding": "Elegant wedding in Berlin",
  "home.chips.corporate": "Office lunch for 40 people",
  "home.chips.private": "Private dinner with service staff",
  "home.chips.ramadan": "Iftar for 120 guests",
  "home.chips.bbq": "BBQ & Grill",
  "home.chips.office": "Office Catering",
  "home.guided.label": "Guided event planning",
  "home.guided.title": "Tell us about your event",
  "home.guided.subtitle": "Start with your event type, guest count, city, and budget. Continue into a structured request flow and discover relevant caterers.",
  "home.guided.eventType": "Event Type",
  "home.guided.eventTypeValue": "Wedding / Business Event / Private Party",
  "home.guided.guests": "Guest Count",
  "home.guided.guestsValue": "20 to 300+ guests",
  "home.guided.budget": "Budget",
  "home.guided.budgetValue": "Flexible range",
  "home.guided.preferences": "Preferences",
  "home.guided.preferencesValue": "Cuisine, dietary needs, service style, extra services",
  "home.guided.cta": "Start AI event brief",
  "home.why.label": "Why Speisely",
  "home.why.title": "A stronger product experience than a simple caterer list.",
  "home.why.subtitle": "Speisely should feel premium, guided, and useful from the first click. The website introduces the brand, and the product flow helps users move naturally into planning their event.",
  "home.highlight1.title": "Curated Caterers",
  "home.highlight1.desc": "Browse selected providers for weddings, corporate events, family celebrations, and premium private occasions.",
  "home.highlight2.title": "Smart Event Matching",
  "home.highlight2.desc": "Tell us about your event and continue into a guided request flow designed to help you discover suitable caterers.",
  "home.highlight3.title": "Flexible for Every Occasion",
  "home.highlight3.desc": "From buffet and finger food to plated menus and full-service staffing, Speisely supports different event formats.",
  "home.highlight4.title": "One Clear Journey",
  "home.highlight4.desc": "Start on the website, explore caterers, submit your request, and continue seamlessly into your dashboard.",
  "home.occasions.label": "Occasions",
  "home.occasions.title": "Explore catering by occasion",
  "home.occasions.viewAll": "Browse all caterers",
  "home.occasions.cardCta": "Start request",
  "home.occasions.wedding": "Wedding",
  "home.occasions.weddingDesc": "Elegant catering for celebrations, receptions, and full-day events.",
  "home.occasions.corporate": "Business Event",
  "home.occasions.corporateDesc": "Modern catering for office gatherings, conferences, launches, and team events.",
  "home.occasions.private": "Private Party",
  "home.occasions.privateDesc": "Flexible menus for birthdays, anniversaries, family dinners, and celebrations.",
  "home.occasions.ramadan": "Ramadan / Iftar",
  "home.occasions.ramadanDesc": "Event-ready options for community dinners, family gatherings, and special evenings.",
  "home.steps.label": "How it works",
  "home.steps.title": "A cleaner path from discovery to event planning",
  "home.steps.subtitle": "Instead of throwing users into a confusing marketplace, Speisely can guide them into the right next step.",
  "home.steps.step1Title": "Describe Your Event",
  "home.steps.step1Desc": "Share the event type, guest count, location, budget, and preferences.",
  "home.steps.step2Title": "Discover Suitable Caterers",
  "home.steps.step2Desc": "Browse profiles and continue into a request flow that helps you find relevant options.",
  "home.steps.step3Title": "Compare and Continue",
  "home.steps.step3Desc": "Review your request, explore caterers, and continue your journey through the dashboard.",
  "home.footerTagline": "Premium catering marketplace for modern event planning.",
  "home.editorialHeroTitle": "Describe your event. Get matched with the right caterers.",
  "home.editorialHeroSubtitle": "Speisely turns your event idea into a clearer catering brief — then helps you discover caterers that fit your style, budget, guest count, and dietary needs.",
  "home.editorialSearchPlaceholder": "Wedding for 80 guests in Berlin, mostly vegetarian, elegant, around €35 per person",
  "home.heroBenefit1": "Natural-language event input",
  "home.heroBenefit2": "Smarter matching",
  "home.heroBenefit3": "Premium catering discovery",
  "home.heroPanel.label": "Curated request",
  "home.heroPanel.title": "A clearer start for event catering",
  "home.heroPanel.badge": "Premium",
  "home.heroPanel.occasionDesc": "Refined service, seasonal menu direction, and premium presentation.",
  "home.heroPanel.guestLabel": "Guest count",
  "home.heroPanel.guestValue": "20 to 300+",
  "home.heroPanel.notesLabel": "Selection notes",
  "home.heroPanel.notesValue": "Cuisine, dietary preferences, service format, budget, city",
  "home.heroPanel.tag1": "Weddings",
  "home.heroPanel.tag2": "Business Events",
  "home.heroPanel.tag3": "Private Occasions",
  "home.principles.label": "How it works",
  "home.principles.title": "From event idea to a better shortlist",
  "home.principles.subtitle": "Instead of sending you into a long directory, Speisely helps structure your request and guide you toward more relevant caterers.",
  "home.principles.item1Title": "Curated discovery",
  "home.principles.item1Desc": "Start from the occasion — not from endless filters and scattered listings.",
  "home.principles.item2Title": "Structured selection",
  "home.principles.item2Desc": "Turn event details into a request that actually helps caterers respond well.",
  "home.principles.item3Title": "Clear continuation",
  "home.principles.item3Desc": "Move naturally from website discovery into your dashboard and booking flow.",
  "home.languagesLabel": "Multilingual advantage",
  "home.languagesTitle": "German first. Plus English, Turkish, and Arabic.",
  "home.languagesSubtitle": "Speisely can welcome customers in multiple languages — a real advantage for diverse events, international teams, and modern hosts.",
  "home.editorialOccasionsTitle": "Start with the occasion, then refine with Speisely",
  "home.editorialStepsTitle": "See how Speisely understands your event",
  "home.editorialStepsSubtitle": "A simple request becomes a more structured catering brief — making discovery faster, clearer, and more relevant.",
  "home.editorialCtaLabel": "Start planning",
  "home.editorialCtaTitle": "Start with your event, not a directory.",
  "home.editorialCtaSubtitle": "Tell Speisely what you are planning and continue with a smarter catering request flow.",
  "home.editorialCtaPrimary": "Describe your event",
  "home.editorialCtaSecondary": "Browse caterers",
  "home.editorialFooterTagline": "Speisely combines premium caterer discovery with AI-guided event intake for modern events.",
  "home.images.heroAlt": "Premium catering presentation",
  "home.images.businessAlt": "Business catering presentation",
  "home.images.ctaAlt": "Private catering presentation",
  "home.aiDemo.requestLabel": "Your request",
  "home.aiDemo.request": "Wedding for 80 guests in Berlin, mostly vegetarian, elegant, around €35 per person",
  "home.aiDemo.understands": "Speisely understands",
  "home.aiDemo.recommended": "Suggested matches",
  "home.aiDemo.tagEvent": "Wedding",
  "home.aiDemo.tagCity": "Berlin",
  "home.aiDemo.tagGuests": "80 guests",
  "home.aiDemo.tagDiet": "Vegetarian",
  "home.aiDemo.tagStyle": "Elegant",
  "home.aiDemo.tagBudget": "€35 / person",
  "home.aiDemo.caterer1Name": "Berliner Genussküche",
  "home.aiDemo.caterer1Meta": "Fine Dining · Vegetarian",
  "home.aiDemo.caterer2Name": "Grüne Tafel Events",
  "home.aiDemo.caterer2Meta": "Weddings · Organic",
  "home.aiDemo.caterer3Name": "Villa Catering",
  "home.aiDemo.caterer3Meta": "Premium · Multi-cuisine"
