/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SpeiselyRouteImport } from './routes/speisely'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as InstantOrderRouteImport } from './routes/instant-order'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlannerIndexRouteImport } from './routes/planner.index'
import { Route as CateringIndexRouteImport } from './routes/catering.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RestaurantSlugRouteImport } from './routes/restaurant.$slug'
import { Route as PlannerSlugRouteImport } from './routes/planner.$slug'
import { Route as CateringInstitutionalCateringRouteImport } from './routes/catering.institutional-catering'
import { Route as CateringEventsRouteImport } from './routes/catering.events'
import { Route as CateringDailyCateringSubscriptionsRouteImport } from './routes/catering.daily-catering-subscriptions'
import { Route as CateringSlugRouteImport } from './routes/catering.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthenticatedRestaurantRouteImport } from './routes/_authenticated/restaurant'
import { Route as AuthenticatedCustomerRouteImport } from './routes/_authenticated/customer'
import { Route as AuthenticatedCatererRouteImport } from './routes/_authenticated/caterer'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as ReviewIntakeTokenRouteImport } from './routes/review.intake.$token'
import { Route as RestaurantsOrtCityRouteImport } from './routes/restaurants.ort.$city'
import { Route as PlannerOrtCityRouteImport } from './routes/planner.ort.$city'
import { Route as CheckoutDepositBookingIdRouteImport } from './routes/checkout.deposit.$bookingId'
import { Route as CateringOrtCityRouteImport } from './routes/catering.ort.$city'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as AuthenticatedRestaurantReviewsRouteImport } from './routes/_authenticated/restaurant.reviews'
import { Route as AuthenticatedRestaurantKitchenRouteImport } from './routes/_authenticated/restaurant.kitchen'
import { Route as AuthenticatedDashboardPlannerRouteImport } from './routes/_authenticated/dashboard/planner'
import { Route as AuthenticatedCatererReviewsRouteImport } from './routes/_authenticated/caterer.reviews'
import { Route as EmbedPlannerSlugInquiryRouteImport } from './routes/embed.planner.$slug.inquiry'
import { Route as EmbedCateringSlugBriefIntakeRouteImport } from './routes/embed.catering.$slug.brief-intake'
import { Route as ApiStripeConnectCallbackRouteImport } from './routes/api.stripe.connect.callback'
import { Route as AuthenticatedDashboardPlannerReviewsRouteImport } from './routes/_authenticated/dashboard.planner.reviews'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeiselyRoute = SpeiselyRouteImport.update({
  id: '/speisely',
  path: '/speisely',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const InstantOrderRoute = InstantOrderRouteImport.update({
  id: '/instant-order',
  path: '/instant-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlannerRoute,
} as any)
const CateringIndexRoute = CateringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CateringRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSlugRoute = RestaurantSlugRouteImport.update({
  id: '/restaurant/$slug',
  path: '/restaurant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerSlugRoute = PlannerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlannerRoute,
} as any)
const CateringInstitutionalCateringRoute =
  CateringInstitutionalCateringRouteImport.update({
    id: '/institutional-catering',
    path: '/institutional-catering',
    getParentRoute: () => CateringRoute,
  } as any)
const CateringEventsRoute = CateringEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CateringRoute,
} as any)
const CateringDailyCateringSubscriptionsRoute =
  CateringDailyCateringSubscriptionsRouteImport.update({
    id: '/daily-catering-subscriptions',
    path: '/daily-catering-subscriptions',
    getParentRoute: () => CateringRoute,
  } as any)
const CateringSlugRoute = CateringSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CateringRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedRestaurantRoute = AuthenticatedRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerRoute = AuthenticatedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatererRoute = AuthenticatedCatererRouteImport.update({
  id: '/caterer',
  path: '/caterer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ReviewIntakeTokenRoute = ReviewIntakeTokenRouteImport.update({
  id: '/review/intake/$token',
  path: '/review/intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsOrtCityRoute = RestaurantsOrtCityRouteImport.update({
  id: '/restaurants/ort/$city',
  path: '/restaurants/ort/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerOrtCityRoute = PlannerOrtCityRouteImport.update({
  id: '/ort/$city',
  path: '/ort/$city',
  getParentRoute: () => PlannerRoute,
} as any)
const CheckoutDepositBookingIdRoute =
  CheckoutDepositBookingIdRouteImport.update({
    id: '/checkout/deposit/$bookingId',
    path: '/checkout/deposit/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CateringOrtCityRoute = CateringOrtCityRouteImport.update({
  id: '/ort/$city',
  path: '/ort/$city',
  getParentRoute: () => CateringRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRestaurantReviewsRoute =
  AuthenticatedRestaurantReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedRestaurantRoute,
  } as any)
const AuthenticatedRestaurantKitchenRoute =
  AuthenticatedRestaurantKitchenRouteImport.update({
    id: '/kitchen',
    path: '/kitchen',
    getParentRoute: () => AuthenticatedRestaurantRoute,
  } as any)
const AuthenticatedDashboardPlannerRoute =
  AuthenticatedDashboardPlannerRouteImport.update({
    id: '/dashboard/planner',
    path: '/dashboard/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatererReviewsRoute =
  AuthenticatedCatererReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedCatererRoute,
  } as any)
const EmbedPlannerSlugInquiryRoute = EmbedPlannerSlugInquiryRouteImport.update({
  id: '/embed/planner/$slug/inquiry',
  path: '/embed/planner/$slug/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCateringSlugBriefIntakeRoute =
  EmbedCateringSlugBriefIntakeRouteImport.update({
    id: '/embed/catering/$slug/brief-intake',
    path: '/embed/catering/$slug/brief-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeConnectCallbackRoute =
  ApiStripeConnectCallbackRouteImport.update({
    id: '/api/stripe/connect/callback',
    path: '/api/stripe/connect/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardPlannerReviewsRoute =
  AuthenticatedDashboardPlannerReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardPlannerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/catering': typeof CateringRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/instant-order': typeof InstantOrderRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/partners': typeof PartnersRoute
  '/planner': typeof PlannerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speisely': typeof SpeiselyRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/caterer': typeof AuthenticatedCatererRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRoute
  '/restaurant': typeof AuthenticatedRestaurantRouteWithChildren
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catering/$slug': typeof CateringSlugRoute
  '/catering/daily-catering-subscriptions': typeof CateringDailyCateringSubscriptionsRoute
  '/catering/events': typeof CateringEventsRoute
  '/catering/institutional-catering': typeof CateringInstitutionalCateringRoute
  '/planner/$slug': typeof PlannerSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/catering/': typeof CateringIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/caterer/reviews': typeof AuthenticatedCatererReviewsRoute
  '/dashboard/planner': typeof AuthenticatedDashboardPlannerRouteWithChildren
  '/restaurant/kitchen': typeof AuthenticatedRestaurantKitchenRoute
  '/restaurant/reviews': typeof AuthenticatedRestaurantReviewsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/catering/ort/$city': typeof CateringOrtCityRoute
  '/checkout/deposit/$bookingId': typeof CheckoutDepositBookingIdRoute
  '/planner/ort/$city': typeof PlannerOrtCityRoute
  '/restaurants/ort/$city': typeof RestaurantsOrtCityRoute
  '/review/intake/$token': typeof ReviewIntakeTokenRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/planner/reviews': typeof AuthenticatedDashboardPlannerReviewsRoute
  '/api/stripe/connect/callback': typeof ApiStripeConnectCallbackRoute
  '/embed/catering/$slug/brief-intake': typeof EmbedCateringSlugBriefIntakeRoute
  '/embed/planner/$slug/inquiry': typeof EmbedPlannerSlugInquiryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/instant-order': typeof InstantOrderRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/partners': typeof PartnersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speisely': typeof SpeiselyRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/caterer': typeof AuthenticatedCatererRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRoute
  '/restaurant': typeof AuthenticatedRestaurantRouteWithChildren
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catering/$slug': typeof CateringSlugRoute
  '/catering/daily-catering-subscriptions': typeof CateringDailyCateringSubscriptionsRoute
  '/catering/events': typeof CateringEventsRoute
  '/catering/institutional-catering': typeof CateringInstitutionalCateringRoute
  '/planner/$slug': typeof PlannerSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/blog': typeof BlogIndexRoute
  '/catering': typeof CateringIndexRoute
  '/planner': typeof PlannerIndexRoute
  '/caterer/reviews': typeof AuthenticatedCatererReviewsRoute
  '/dashboard/planner': typeof AuthenticatedDashboardPlannerRouteWithChildren
  '/restaurant/kitchen': typeof AuthenticatedRestaurantKitchenRoute
  '/restaurant/reviews': typeof AuthenticatedRestaurantReviewsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/catering/ort/$city': typeof CateringOrtCityRoute
  '/checkout/deposit/$bookingId': typeof CheckoutDepositBookingIdRoute
  '/planner/ort/$city': typeof PlannerOrtCityRoute
  '/restaurants/ort/$city': typeof RestaurantsOrtCityRoute
  '/review/intake/$token': typeof ReviewIntakeTokenRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/planner/reviews': typeof AuthenticatedDashboardPlannerReviewsRoute
  '/api/stripe/connect/callback': typeof ApiStripeConnectCallbackRoute
  '/embed/catering/$slug/brief-intake': typeof EmbedCateringSlugBriefIntakeRoute
  '/embed/planner/$slug/inquiry': typeof EmbedPlannerSlugInquiryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/catering': typeof CateringRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/instant-order': typeof InstantOrderRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/partners': typeof PartnersRoute
  '/planner': typeof PlannerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speisely': typeof SpeiselyRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/caterer': typeof AuthenticatedCatererRouteWithChildren
  '/_authenticated/customer': typeof AuthenticatedCustomerRoute
  '/_authenticated/restaurant': typeof AuthenticatedRestaurantRouteWithChildren
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catering/$slug': typeof CateringSlugRoute
  '/catering/daily-catering-subscriptions': typeof CateringDailyCateringSubscriptionsRoute
  '/catering/events': typeof CateringEventsRoute
  '/catering/institutional-catering': typeof CateringInstitutionalCateringRoute
  '/planner/$slug': typeof PlannerSlugRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/catering/': typeof CateringIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/_authenticated/caterer/reviews': typeof AuthenticatedCatererReviewsRoute
  '/_authenticated/dashboard/planner': typeof AuthenticatedDashboardPlannerRouteWithChildren
  '/_authenticated/restaurant/kitchen': typeof AuthenticatedRestaurantKitchenRoute
  '/_authenticated/restaurant/reviews': typeof AuthenticatedRestaurantReviewsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/catering/ort/$city': typeof CateringOrtCityRoute
  '/checkout/deposit/$bookingId': typeof CheckoutDepositBookingIdRoute
  '/planner/ort/$city': typeof PlannerOrtCityRoute
  '/restaurants/ort/$city': typeof RestaurantsOrtCityRoute
  '/review/intake/$token': typeof ReviewIntakeTokenRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/planner/reviews': typeof AuthenticatedDashboardPlannerReviewsRoute
  '/api/stripe/connect/callback': typeof ApiStripeConnectCallbackRoute
  '/embed/catering/$slug/brief-intake': typeof EmbedCateringSlugBriefIntakeRoute
  '/embed/planner/$slug/inquiry': typeof EmbedPlannerSlugInquiryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/catering'
    | '/contact'
    | '/faq'
    | '/impressum'
    | '/instant-order'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/partners'
    | '/planner'
    | '/sitemap.xml'
    | '/speisely'
    | '/ueber-uns'
    | '/verify-email'
    | '/caterer'
    | '/customer'
    | '/restaurant'
    | '/auth/update-password'
    | '/blog/$slug'
    | '/catering/$slug'
    | '/catering/daily-catering-subscriptions'
    | '/catering/events'
    | '/catering/institutional-catering'
    | '/planner/$slug'
    | '/restaurant/$slug'
    | '/blog/'
    | '/catering/'
    | '/planner/'
    | '/caterer/reviews'
    | '/dashboard/planner'
    | '/restaurant/kitchen'
    | '/restaurant/reviews'
    | '/api/webhooks/stripe'
    | '/catering/ort/$city'
    | '/checkout/deposit/$bookingId'
    | '/planner/ort/$city'
    | '/restaurants/ort/$city'
    | '/review/intake/$token'
    | '/dashboard/'
    | '/dashboard/planner/reviews'
    | '/api/stripe/connect/callback'
    | '/embed/catering/$slug/brief-intake'
    | '/embed/planner/$slug/inquiry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/impressum'
    | '/instant-order'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/partners'
    | '/sitemap.xml'
    | '/speisely'
    | '/ueber-uns'
    | '/verify-email'
    | '/caterer'
    | '/customer'
    | '/restaurant'
    | '/auth/update-password'
    | '/blog/$slug'
    | '/catering/$slug'
    | '/catering/daily-catering-subscriptions'
    | '/catering/events'
    | '/catering/institutional-catering'
    | '/planner/$slug'
    | '/restaurant/$slug'
    | '/blog'
    | '/catering'
    | '/planner'
    | '/caterer/reviews'
    | '/dashboard/planner'
    | '/restaurant/kitchen'
    | '/restaurant/reviews'
    | '/api/webhooks/stripe'
    | '/catering/ort/$city'
    | '/checkout/deposit/$bookingId'
    | '/planner/ort/$city'
    | '/restaurants/ort/$city'
    | '/review/intake/$token'
    | '/dashboard'
    | '/dashboard/planner/reviews'
    | '/api/stripe/connect/callback'
    | '/embed/catering/$slug/brief-intake'
    | '/embed/planner/$slug/inquiry'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/catering'
    | '/contact'
    | '/faq'
    | '/impressum'
    | '/instant-order'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/partners'
    | '/planner'
    | '/sitemap.xml'
    | '/speisely'
    | '/ueber-uns'
    | '/verify-email'
    | '/_authenticated/caterer'
    | '/_authenticated/customer'
    | '/_authenticated/restaurant'
    | '/auth/update-password'
    | '/blog/$slug'
    | '/catering/$slug'
    | '/catering/daily-catering-subscriptions'
    | '/catering/events'
    | '/catering/institutional-catering'
    | '/planner/$slug'
    | '/restaurant/$slug'
    | '/blog/'
    | '/catering/'
    | '/planner/'
    | '/_authenticated/caterer/reviews'
    | '/_authenticated/dashboard/planner'
    | '/_authenticated/restaurant/kitchen'
    | '/_authenticated/restaurant/reviews'
    | '/api/webhooks/stripe'
    | '/catering/ort/$city'
    | '/checkout/deposit/$bookingId'
    | '/planner/ort/$city'
    | '/restaurants/ort/$city'
    | '/review/intake/$token'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/planner/reviews'
    | '/api/stripe/connect/callback'
    | '/embed/catering/$slug/brief-intake'
    | '/embed/planner/$slug/inquiry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  CateringRoute: typeof CateringRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ImpressumRoute: typeof ImpressumRoute
  InstantOrderRoute: typeof InstantOrderRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PartnersRoute: typeof PartnersRoute
  PlannerRoute: typeof PlannerRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeiselyRoute: typeof SpeiselyRoute
  UeberUnsRoute: typeof UeberUnsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RestaurantSlugRoute: typeof RestaurantSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  CheckoutDepositBookingIdRoute: typeof CheckoutDepositBookingIdRoute
  RestaurantsOrtCityRoute: typeof RestaurantsOrtCityRoute
  ReviewIntakeTokenRoute: typeof ReviewIntakeTokenRoute
  ApiStripeConnectCallbackRoute: typeof ApiStripeConnectCallbackRoute
  EmbedCateringSlugBriefIntakeRoute: typeof EmbedCateringSlugBriefIntakeRoute
  EmbedPlannerSlugInquiryRoute: typeof EmbedPlannerSlugInquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speisely': {
      id: '/speisely'
      path: '/speisely'
      fullPath: '/speisely'
      preLoaderRoute: typeof SpeiselyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instant-order': {
      id: '/instant-order'
      path: '/instant-order'
      fullPath: '/instant-order'
      preLoaderRoute: typeof InstantOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/': {
      id: '/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/catering/': {
      id: '/catering/'
      path: '/'
      fullPath: '/catering/'
      preLoaderRoute: typeof CateringIndexRouteImport
      parentRoute: typeof CateringRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$slug': {
      id: '/restaurant/$slug'
      path: '/restaurant/$slug'
      fullPath: '/restaurant/$slug'
      preLoaderRoute: typeof RestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/$slug': {
      id: '/planner/$slug'
      path: '/$slug'
      fullPath: '/planner/$slug'
      preLoaderRoute: typeof PlannerSlugRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/catering/institutional-catering': {
      id: '/catering/institutional-catering'
      path: '/institutional-catering'
      fullPath: '/catering/institutional-catering'
      preLoaderRoute: typeof CateringInstitutionalCateringRouteImport
      parentRoute: typeof CateringRoute
    }
    '/catering/events': {
      id: '/catering/events'
      path: '/events'
      fullPath: '/catering/events'
      preLoaderRoute: typeof CateringEventsRouteImport
      parentRoute: typeof CateringRoute
    }
    '/catering/daily-catering-subscriptions': {
      id: '/catering/daily-catering-subscriptions'
      path: '/daily-catering-subscriptions'
      fullPath: '/catering/daily-catering-subscriptions'
      preLoaderRoute: typeof CateringDailyCateringSubscriptionsRouteImport
      parentRoute: typeof CateringRoute
    }
    '/catering/$slug': {
      id: '/catering/$slug'
      path: '/$slug'
      fullPath: '/catering/$slug'
      preLoaderRoute: typeof CateringSlugRouteImport
      parentRoute: typeof CateringRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/restaurant': {
      id: '/_authenticated/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof AuthenticatedRestaurantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caterer': {
      id: '/_authenticated/caterer'
      path: '/caterer'
      fullPath: '/caterer'
      preLoaderRoute: typeof AuthenticatedCatererRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/review/intake/$token': {
      id: '/review/intake/$token'
      path: '/review/intake/$token'
      fullPath: '/review/intake/$token'
      preLoaderRoute: typeof ReviewIntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/ort/$city': {
      id: '/restaurants/ort/$city'
      path: '/restaurants/ort/$city'
      fullPath: '/restaurants/ort/$city'
      preLoaderRoute: typeof RestaurantsOrtCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/ort/$city': {
      id: '/planner/ort/$city'
      path: '/ort/$city'
      fullPath: '/planner/ort/$city'
      preLoaderRoute: typeof PlannerOrtCityRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/checkout/deposit/$bookingId': {
      id: '/checkout/deposit/$bookingId'
      path: '/checkout/deposit/$bookingId'
      fullPath: '/checkout/deposit/$bookingId'
      preLoaderRoute: typeof CheckoutDepositBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering/ort/$city': {
      id: '/catering/ort/$city'
      path: '/ort/$city'
      fullPath: '/catering/ort/$city'
      preLoaderRoute: typeof CateringOrtCityRouteImport
      parentRoute: typeof CateringRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/restaurant/reviews': {
      id: '/_authenticated/restaurant/reviews'
      path: '/reviews'
      fullPath: '/restaurant/reviews'
      preLoaderRoute: typeof AuthenticatedRestaurantReviewsRouteImport
      parentRoute: typeof AuthenticatedRestaurantRoute
    }
    '/_authenticated/restaurant/kitchen': {
      id: '/_authenticated/restaurant/kitchen'
      path: '/kitchen'
      fullPath: '/restaurant/kitchen'
      preLoaderRoute: typeof AuthenticatedRestaurantKitchenRouteImport
      parentRoute: typeof AuthenticatedRestaurantRoute
    }
    '/_authenticated/dashboard/planner': {
      id: '/_authenticated/dashboard/planner'
      path: '/dashboard/planner'
      fullPath: '/dashboard/planner'
      preLoaderRoute: typeof AuthenticatedDashboardPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caterer/reviews': {
      id: '/_authenticated/caterer/reviews'
      path: '/reviews'
      fullPath: '/caterer/reviews'
      preLoaderRoute: typeof AuthenticatedCatererReviewsRouteImport
      parentRoute: typeof AuthenticatedCatererRoute
    }
    '/embed/planner/$slug/inquiry': {
      id: '/embed/planner/$slug/inquiry'
      path: '/embed/planner/$slug/inquiry'
      fullPath: '/embed/planner/$slug/inquiry'
      preLoaderRoute: typeof EmbedPlannerSlugInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/catering/$slug/brief-intake': {
      id: '/embed/catering/$slug/brief-intake'
      path: '/embed/catering/$slug/brief-intake'
      fullPath: '/embed/catering/$slug/brief-intake'
      preLoaderRoute: typeof EmbedCateringSlugBriefIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/connect/callback': {
      id: '/api/stripe/connect/callback'
      path: '/api/stripe/connect/callback'
      fullPath: '/api/stripe/connect/callback'
      preLoaderRoute: typeof ApiStripeConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/planner/reviews': {
      id: '/_authenticated/dashboard/planner/reviews'
      path: '/reviews'
      fullPath: '/dashboard/planner/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardPlannerReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardPlannerRoute
    }
  }
}

interface AuthenticatedCatererRouteChildren {
  AuthenticatedCatererReviewsRoute: typeof AuthenticatedCatererReviewsRoute
}

const AuthenticatedCatererRouteChildren: AuthenticatedCatererRouteChildren = {
  AuthenticatedCatererReviewsRoute: AuthenticatedCatererReviewsRoute,
}

const AuthenticatedCatererRouteWithChildren =
  AuthenticatedCatererRoute._addFileChildren(AuthenticatedCatererRouteChildren)

interface AuthenticatedRestaurantRouteChildren {
  AuthenticatedRestaurantKitchenRoute: typeof AuthenticatedRestaurantKitchenRoute
  AuthenticatedRestaurantReviewsRoute: typeof AuthenticatedRestaurantReviewsRoute
}

const AuthenticatedRestaurantRouteChildren: AuthenticatedRestaurantRouteChildren =
  {
    AuthenticatedRestaurantKitchenRoute: AuthenticatedRestaurantKitchenRoute,
    AuthenticatedRestaurantReviewsRoute: AuthenticatedRestaurantReviewsRoute,
  }

const AuthenticatedRestaurantRouteWithChildren =
  AuthenticatedRestaurantRoute._addFileChildren(
    AuthenticatedRestaurantRouteChildren,
  )

interface AuthenticatedDashboardPlannerRouteChildren {
  AuthenticatedDashboardPlannerReviewsRoute: typeof AuthenticatedDashboardPlannerReviewsRoute
}

const AuthenticatedDashboardPlannerRouteChildren: AuthenticatedDashboardPlannerRouteChildren =
  {
    AuthenticatedDashboardPlannerReviewsRoute:
      AuthenticatedDashboardPlannerReviewsRoute,
  }

const AuthenticatedDashboardPlannerRouteWithChildren =
  AuthenticatedDashboardPlannerRoute._addFileChildren(
    AuthenticatedDashboardPlannerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatererRoute: typeof AuthenticatedCatererRouteWithChildren
  AuthenticatedCustomerRoute: typeof AuthenticatedCustomerRoute
  AuthenticatedRestaurantRoute: typeof AuthenticatedRestaurantRouteWithChildren
  AuthenticatedDashboardPlannerRoute: typeof AuthenticatedDashboardPlannerRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatererRoute: AuthenticatedCatererRouteWithChildren,
  AuthenticatedCustomerRoute: AuthenticatedCustomerRoute,
  AuthenticatedRestaurantRoute: AuthenticatedRestaurantRouteWithChildren,
  AuthenticatedDashboardPlannerRoute:
    AuthenticatedDashboardPlannerRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CateringRouteChildren {
  CateringSlugRoute: typeof CateringSlugRoute
  CateringDailyCateringSubscriptionsRoute: typeof CateringDailyCateringSubscriptionsRoute
  CateringEventsRoute: typeof CateringEventsRoute
  CateringInstitutionalCateringRoute: typeof CateringInstitutionalCateringRoute
  CateringIndexRoute: typeof CateringIndexRoute
  CateringOrtCityRoute: typeof CateringOrtCityRoute
}

const CateringRouteChildren: CateringRouteChildren = {
  CateringSlugRoute: CateringSlugRoute,
  CateringDailyCateringSubscriptionsRoute:
    CateringDailyCateringSubscriptionsRoute,
  CateringEventsRoute: CateringEventsRoute,
  CateringInstitutionalCateringRoute: CateringInstitutionalCateringRoute,
  CateringIndexRoute: CateringIndexRoute,
  CateringOrtCityRoute: CateringOrtCityRoute,
}

const CateringRouteWithChildren = CateringRoute._addFileChildren(
  CateringRouteChildren,
)

interface PlannerRouteChildren {
  PlannerSlugRoute: typeof PlannerSlugRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
  PlannerOrtCityRoute: typeof PlannerOrtCityRoute
}

const PlannerRouteChildren: PlannerRouteChildren = {
  PlannerSlugRoute: PlannerSlugRoute,
  PlannerIndexRoute: PlannerIndexRoute,
  PlannerOrtCityRoute: PlannerOrtCityRoute,
}

const PlannerRouteWithChildren =
  PlannerRoute._addFileChildren(PlannerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  CateringRoute: CateringRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ImpressumRoute: ImpressumRoute,
  InstantOrderRoute: InstantOrderRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PartnersRoute: PartnersRoute,
  PlannerRoute: PlannerRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeiselyRoute: SpeiselyRoute,
  UeberUnsRoute: UeberUnsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  RestaurantSlugRoute: RestaurantSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  CheckoutDepositBookingIdRoute: CheckoutDepositBookingIdRoute,
  RestaurantsOrtCityRoute: RestaurantsOrtCityRoute,
  ReviewIntakeTokenRoute: ReviewIntakeTokenRoute,
  ApiStripeConnectCallbackRoute: ApiStripeConnectCallbackRoute,
  EmbedCateringSlugBriefIntakeRoute: EmbedCateringSlugBriefIntakeRoute,
  EmbedPlannerSlugInquiryRoute: EmbedPlannerSlugInquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
